# Generated by Django 4.1.1 on 2022-09-29 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainapp', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleWorker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pairs_shoes', models.PositiveSmallIntegerField(verbose_name='Пара обуви')),
                ('price', models.PositiveSmallIntegerField(verbose_name='Цена')),
                ('catalog', models.ManyToManyField(to='mainapp.catalog', verbose_name='Каталог')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.worker', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Журнал продаж',
                'verbose_name_plural': 'Журналы продаж',
            },
        ),
    ]
