# Generated by Django 4.1.1 on 2022-10-03 17:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Ф.И.О.')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/Worker/%Y', verbose_name='Фото')),
                ('phone', models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator(message='+996111222333', regex='^\\+?1?\\d{9,20}$')], verbose_name='Номер телефона')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, unique=True, verbose_name='Почта')),
                ('job_title', models.CharField(choices=[('Техничка', 'Техничка'), ('Повар', 'Повар'), ('Швея', 'Швея'), ('Работник ПУ', 'Работник ПУ'), ('Работник ЭВА', 'Работник ЭВА'), ('Работник', 'Работник')], max_length=255, verbose_name='Должность')),
                ('date_joined', models.DateField(blank=True, null=True, verbose_name='Дата регистрации')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='TabelWorkers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True, verbose_name='Дата')),
                ('quantity_of_PU', models.PositiveSmallIntegerField(verbose_name='Количество пар ПУ')),
                ('quantity_of_EVA', models.PositiveSmallIntegerField(verbose_name='Количество пар ЭВА')),
                ('total_quantity', models.PositiveSmallIntegerField(verbose_name='Общее количество')),
                ('total_defect', models.PositiveSmallIntegerField(default=0, verbose_name='Общее браки')),
                ('price_of_single_mmodel', models.PositiveSmallIntegerField(verbose_name='цена')),
                ('total_price_of_one_worker', models.PositiveSmallIntegerField(verbose_name='Полная цена')),
                ('worker', models.ManyToManyField(to='staff.worker', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Табель сотрудника',
                'verbose_name_plural': 'Табель сотрудников',
            },
        ),
    ]
