# Generated by Django 4.1.1 on 2022-09-29 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Бренд обуви')),
            ],
            options={
                'verbose_name': 'Бренд обуви',
                'verbose_name_plural': 'Бренды обуви',
            },
        ),
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=20, verbose_name='Код товара')),
                ('color', models.CharField(max_length=50, verbose_name='Цвет')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='images/catalog', verbose_name='Изображение')),
                ('size_from', models.PositiveSmallIntegerField(verbose_name='Размер от')),
                ('size_to', models.PositiveSmallIntegerField(verbose_name='Размер до')),
                ('articul', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.brand', verbose_name='Артикул(Бренд товара)')),
            ],
            options={
                'verbose_name': 'Каталог',
                'verbose_name_plural': 'Каталоги',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название страны')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
            },
        ),
        migrations.CreateModel(
            name='Semifinished',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('quantity', models.PositiveSmallIntegerField(verbose_name='Количество')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.country', verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Полуфабрикат',
                'verbose_name_plural': 'Полуфабрикаты',
            },
        ),
        migrations.CreateModel(
            name='Elaboration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_of_pairs', models.PositiveSmallIntegerField(verbose_name='Сколько произведено')),
                ('quantity_of_packages', models.PositiveSmallIntegerField(verbose_name='Сколько упаковок')),
                ('defect_working', models.PositiveSmallIntegerField(verbose_name='рабочий брак')),
                ('quantity_of_PU', models.PositiveSmallIntegerField(verbose_name='Количество пар ПУ')),
                ('quantity_of_EVA', models.PositiveSmallIntegerField(verbose_name='Количество пар ЭВА')),
                ('defect_EVA', models.PositiveSmallIntegerField(verbose_name='Брак ЭВА')),
                ('defect_PU', models.PositiveSmallIntegerField(verbose_name='Брак ПУ')),
                ('date', models.DateField(verbose_name='Дата')),
                ('to_stock', models.PositiveSmallIntegerField(verbose_name='Сколько отправят на склад')),
                ('total_defect', models.PositiveSmallIntegerField(verbose_name='Общее количество брака')),
                ('total_price', models.PositiveSmallIntegerField(verbose_name='Общая цена')),
                ('catalog', models.ManyToManyField(to='mainapp.catalog', verbose_name='Каталог')),
                ('semifinished', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.semifinished', verbose_name='полуфабрикаты')),
            ],
            options={
                'verbose_name': 'Выработка',
                'verbose_name_plural': 'Выработки',
            },
        ),
    ]
