# Generated by Django 4.1.1 on 2022-10-03 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0001_initial'),
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyDiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveSmallIntegerField(verbose_name='Цена')),
                ('package_pairs', models.PositiveSmallIntegerField(default=6, verbose_name='Сколько пар в одной упаковке')),
                ('quantity_of_PU', models.PositiveSmallIntegerField(verbose_name='Количество пар ПУ')),
                ('quantity_of_EVA', models.PositiveSmallIntegerField(verbose_name='Количество пар ЭВА')),
                ('worker_defect', models.PositiveSmallIntegerField(verbose_name='Количество рабочего брака')),
                ('SAYA_defect', models.PositiveSmallIntegerField(verbose_name='Количество брака САЯ')),
                ('PU_defect', models.PositiveSmallIntegerField(verbose_name='Количество брака ПУ')),
                ('EVA_defect', models.PositiveSmallIntegerField(verbose_name='Количество брака ЭВА')),
                ('date', models.DateField(null=True, verbose_name='Дата')),
                ('catalog', models.ManyToManyField(to='mainapp.catalog', verbose_name='Каталог')),
                ('semifinished', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.semifinished', verbose_name='Полуфабрикаты')),
                ('worker', models.ManyToManyField(to='staff.worker', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Ежедневка',
                'verbose_name_plural': 'Ежедневки',
            },
        ),
    ]
