# Generated by Django 4.1.1 on 2022-09-29 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelCalendarPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_of_PU', models.PositiveSmallIntegerField(null=True, verbose_name='Количество пар ПУ')),
                ('date', models.DateField(null=True, verbose_name='Дата')),
                ('catalog', models.ManyToManyField(to='mainapp.catalog', verbose_name='Каталог')),
            ],
            options={
                'verbose_name': 'Календарь ПУ',
                'verbose_name_plural': 'Календари ПУ',
            },
        ),
        migrations.CreateModel(
            name='ModelCalendarEVA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_of_EVA', models.PositiveSmallIntegerField(null=True, verbose_name='Количество пар ЭВА')),
                ('date', models.DateField(null=True, verbose_name='Дата')),
                ('catalog', models.ManyToManyField(to='mainapp.catalog', verbose_name='Каталог')),
            ],
            options={
                'verbose_name': 'Календарь ЭВА',
                'verbose_name_plural': 'Календари ЭВА',
            },
        ),
        migrations.CreateModel(
            name='ElaborationCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата')),
                ('catalog', models.ManyToManyField(to='mainapp.catalog', verbose_name='Каталог')),
                ('elaboration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.elaboration', verbose_name='Общий брак')),
            ],
            options={
                'verbose_name': 'Календарь выработки',
                'verbose_name_plural': 'Календари выработки',
            },
        ),
    ]
