# Generated by Django 4.1.1 on 2022-10-03 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockOfDoneProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=0, verbose_name='Количество выработанных продуктов на складе')),
                ('date', models.DateField(null=True, verbose_name='Дата')),
                ('catalog', models.ManyToManyField(to='mainapp.catalog', verbose_name='Каталог')),
            ],
            options={
                'verbose_name': 'Склад готовых продуктов',
                'verbose_name_plural': 'Склад готовых продуктов',
            },
        ),
    ]
